[project]
name = "yolo-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "face-recognition>=1.3.0",
    "kafka-python>=2.3.0",
    "numpy==1.26.4",
    "opencv-python-headless>=4.8.0.74",
    "pyside6>=6.7.0",
    "pyyaml>=6.0.2",
    "ultralytics>=8.3.0,<8.4.0",
]
