FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04

WORKDIR /app

ARG http_proxy
ARG https_proxy
ARG all_proxy
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG ALL_PROXY

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple \
    UV_DEFAULT_INDEX=https://pypi.tuna.tsinghua.edu.cn/simple \
    UV_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple \
    UV_INDEX_STRATEGY=first-index \
    http_proxy=${http_proxy} \
    https_proxy=${https_proxy} \
    all_proxy=${all_proxy} \
    HTTP_PROXY=${HTTP_PROXY} \
    HTTPS_PROXY=${HTTPS_PROXY} \
    ALL_PROXY=${ALL_PROXY}

RUN sed -i 's|http://archive.ubuntu.com/ubuntu|https://mirrors.tuna.tsinghua.edu.cn/ubuntu|g' /etc/apt/sources.list \
    && sed -i 's|http://security.ubuntu.com/ubuntu|https://mirrors.tuna.tsinghua.edu.cn/ubuntu|g' /etc/apt/sources.list

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-dev python3-pip python3-venv \
       libgl1 libglib2.0-0 curl build-essential gfortran libopenblas-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir uv

ENV UV_CACHE_DIR=/root/.cache/uv
COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=cache,target=/root/.cache/pip \
    uv sync --frozen --default-index ${UV_DEFAULT_INDEX}


ENV KAFKA_BOOTSTRAP_SERVERS=localhost:9092 \
    KAFKA_TOPIC=fire-alarm \
    KAFKA_GROUP_ID=fire-alarm-consumer \
    KAFKA_ALARM_TOPIC=fire-alarm-result \
    KAFKA_BATCH_SIZE=10 \
    KAFKA_MAX_WAIT_SEC=2 \
    KAFKA_MAX_BATCHES=0 \
    KAFKA_AUTO_OFFSET_RESET=latest \
    MODEL_PATH=/app/model/fire-kaggle/weights/best.pt \
    MODEL_CONF=0.6 \
    MODEL_DEVICE=cuda \
    MODEL_GPU=0 \
    TARGET_CLASS_NAME=fire \
    TARGET_CLASS_INDEX=0

CMD ["/bin/sh", "-c", "uv run python /app/kafuka/base/alarm_consumer.py \
  --bootstrap-servers ${KAFKA_BOOTSTRAP_SERVERS} \
  --topic ${KAFKA_TOPIC} \
  --group-id ${KAFKA_GROUP_ID} \
  --alarm-topic ${KAFKA_ALARM_TOPIC} \
  --batch-size ${KAFKA_BATCH_SIZE} \
  --max-wait-sec ${KAFKA_MAX_WAIT_SEC} \
  --max-batches ${KAFKA_MAX_BATCHES} \
  --auto-offset-reset ${KAFKA_AUTO_OFFSET_RESET} \
  --model ${MODEL_PATH} \
  --conf ${MODEL_CONF} \
  ${MODEL_DEVICE:+--device ${MODEL_DEVICE}} \
  --gpu ${MODEL_GPU} \
  --target-class-name ${TARGET_CLASS_NAME} \
  --target-class-index ${TARGET_CLASS_INDEX}"]
